project:
  type: manuscript

bibliography: references.bib
cache: true
citation: true
df-print: kable
fig-align: center
fig-width: 5
fig-heigth: 3
fig-dpi: 300
lang: en
lightbox: true
link-external-newwindow: true
mermaid:
  theme: default
notebook-links: false
number-sections: true
warning: false

format:
  html:
    theme: cosmo
    code-fold: true
    css: styles.css
    execute:
      echo: true
    fig-format: jpeg
    include-in-header:
      text: |
        <script defer data-domain="camillemondon.com" src="https://analytics.mondon.xyz/js/script.js"></script>
  arxiv-pdf:
    authorcols: true
    biblatexoptions:
      - style=authoryear
      - backend=biber
      - backref=true
    cite-method: biblatex
    colorlinks: false
    echo: false
    fig-format: pdf
    fig-pos: ht
    link-citations: true
    pdf-engine: pdflatex

knitr:
  opts_knit:
    collapse: true
    comment: "#>"
    warning: false
    dev.args: list(bg = "white")
    root.dir: ./
